image: tmaier/docker-compose:latest

services:
  - docker:dind

build:
  stage: build
  script:
    # - apk add --no-cache python py2-pip
    # - pip install --no-cache-dir docker-compose
    # - docker-compose -v
    - docker-compose build buildkite_ci
    - docker-compose run --rm buildkite_ci bash ci.sh