# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - postgres:latest
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  script:
    - yarn setup
    # - yarn run -s lint
    # - yarn run -s lint
    # - yarn run -s test:unit
    # - yarn run -s test:front
    
test:
  script:
    - yarn run -s lint
    - yarn run -s test:unit
    - yarn run -s test:front

e2e:
  script:
    - sudo apt-get install postgresql-client
