# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - postgres:latest
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

# end to end testing template
e2e_tests: &e2e_tests
    - run:
        name: 'Run E2E Tests'
        command: |
            yarn run -s test:generate-app -- ${DB_STRING}
            yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
            yarn run -s test:e2e


build:
  script:
    - yarn setup
    - yarn run -s lint
    - yarn run -s lint
    - yarn run -s test:unit
    - yarn run -s test:front
    - sudo apt-get install postgresql-client
    - psql -c 'create database strapi_test;' -U postgres -h localhost -p 5432
    - export DB_STRING='--dbclient=postgres --dbhost=localhost --dbport=5432 --dbname=strapi_test --dbusername=postgres --dbpassword='
    - <<: *e2e_tests            
    
# test:
#   script:
#     - yarn run -s lint
#     - yarn run -s test:unit
#     - yarn run -s test:front

# e2e:
#   script:
#     - sudo apt-get install postgresql-client
