image: ubuntu

stack: docker

build_script:
# install docker compose
- sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker-compose build buildkite_ci
- docker-compose run --rm buildkite_ci bash ci.sh