image: Visual Studio 2017

# environment:
#   nodejs_version: "10"

# stack: node 10, mysql, docker

install:
- ps: Install-Product node 10
- yarn setup
- yarn global add -g wait-on

build_script:
- yarn run -s lint
- yarn run -s test:unit
- yarn run -s test:front