version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10
      docker: 18
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - yarn setup
      - yarn global add -g wait-on
      # node_modules symlinks are lost when storing artifacts
      # workaround to make sure all node_modules are stored as artifacts
      - cp -rL node_modules node_modules2
      - rm -rf node_modules
      - mv node_modules2 node_modules
      # - pwd
      # - ls -a
      # - mkdir ./app
      # - touch test.txt
      # - ls -a

  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
#     - location
  # name: strapi-$(date +%Y-%m-%d)
  # discard-paths: no
  # base-directory: location
# cache:
#   paths:
#     # - 'node_modules/**/*'
#     # - '~/.cache'
#     - '/.npm'