version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  build:
    commands:
      - yarn run -s test:generate-app -- '--dbclient=sqlite --dbfile=./tmp/data.db'
      - yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
      - yarn run -s test:e2e