version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 10
      docker: 18
  build:
    commands:
      - docker-compose build buildkite_ci
      - docker-compose run --rm buildkite_ci bash ci.sh