version: '3'

services:
  app:
    image: node:10
    volumes:
      - .:/app

  e2e_tests:
    image: node:10
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mysql
      # - mongo

  postgres_tests:
    image: node:10
    volumes:
      - .:/app
    links:
      - postgres:postgres
    entrypoint: wait-for-it.sh postgres:5432 -s --

  mysql_tests:
    image: node:10
    depends_on:
      - mysql

  postgres:
    image: postgres

  mysql:
    image: mysql


volumes:
  my_dbdata: