version: 2.1

# Define the jobs
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: docker build
                command: docker-compose run --rm app bash yarn-ci.sh