version: 2.1    

# end to end testing template
e2e_tests: &e2e_tests
    - run:
        name: 'Run E2E Tests'
        command: |
            yarn run -s test:generate-app -- ${DB_STRING}
            yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
            yarn run -s test:e2e

# Define the jobs
jobs:
    build:
        working_directory: ~/app
        machine: true
        steps:
            - checkout
            - run:
                name: docker build
                command: docker-compose build buildkite_ci
            - run:
                name: docker run
                command: |
                    docker-compose up -d buildkite_ci /bin/sh -e -c 'echo "*** STARTING Lint and Unit Tests `date` ***"
yarn run snyk auth "a88a53a7-63bb-43f2-a78d-41df1448f757"
echo "*** `date` ***"
yarn run -s test:snyk
echo "*** `date` ***"
yarn run -s lint
echo "*** `date` ***"
yarn run -s test:unit
echo "*** `date` ***"
yarn run -s test:front
echo "*** FINISHED Lint and Unit Tests `date` ***"
echo "*** STARTING Postgres Tests `date` ***"
apt-get update && apt-get install -y postgresql-client
echo "*** `date` ***"
psql -c "create database strapi_test;" -U postgres -h postgres -p 5432
echo "*** `date` ***"
yarn run -s test:generate-app -- "--dbclient=postgres --dbhost=postgres --dbport=5432 --dbname=strapi_test --dbusername=postgres --dbpassword="
yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
yarn run -s test:e2e
echo "*** FINISHED Postgres Tests `date` ***"
echo "*** STARTING MySQL Tests `date` ***"
apt-get install -y mysql-client
yarn run -s test:generate-app -- "--dbclient=mysql --dbhost=mysql --dbport=3306 --dbname=strapi_test --dbusername=ci --dbpassword=passw0rd"
yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
yarn run -s test:e2e
echo "*** FINISHED MySQL Tests `date` ***"
echo "*** STARTING SQLLite Tests `date` ***"
yarn run -s test:generate-app -- "--dbclient=sqlite --dbfile=./tmp/data.db"
yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
yarn run -s test:e2e
echo "*** FINISHED SQLLite Tests `date` ***"
echo "*** STARTING Mongo Tests `date` ***"
yarn run -s test:generate-app -- "--dbclient=mongo --dbhost=mongo --dbport=27017 --dbname=strapi_test --dbusername= --dbpassword="
yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
yarn run -s test:e2e'

workflows:
  version: 2
  build_and_test:
    jobs:   
        - build