version: 2.1

# Define the jobs
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: yarn setup
                command: yarn setup