version: 2.1    

# end to end testing template
e2e_tests: &e2e_tests
    - run:
        name: 'Run E2E Tests'
        command: |
            yarn run -s test:generate-app -- ${DB_STRING}
            yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
            yarn run -s test:e2e

# Define the jobs
jobs:
    build:
        working_directory: ~/app
        machine: true
        steps:
            - checkout
            - run:
                name: docker build
                command: docker-compose build buildkite_ci
            - run:
                name: docker run
                command: docker-compose up -d buildkite_ci
            - run:
                name: tests
                command: |
                    echo "*** STARTING Lint and Unit Tests `date` ***"
                    yarn run -s lint
                    yarn run -s lint
                    yarn run -s test:unit
                    yarn run -s test:front
                    echo "*** FINISHED Lint and Unit Tests `date` ***"

                    # Postgres
                    echo "*** STARTING Postgres Tests `date` ***"
                    apt-get update && apt-get install -y postgresql-client
                    psql -c 'create database strapi_test;' -U postgres -h postgres -p 5432
                    yarn run -s test:generate-app -- '--dbclient=postgres --dbhost=postgres --dbport=5432 --dbname=strapi_test --dbusername=postgres --dbpassword='
                    yarn run -s test:start-app & ./node_modules/.bin/wait-on http://localhost:1337
                    yarn run -s test:e2e      
                    echo "*** FINISHED Postgres Tests `date` ***"

workflows:
  version: 2
  build_and_test:
    jobs:   
        - build