version: 2.0

workflows:
  version: 2
  build_and_test:
    jobs:   
        - build:
        working_directory: ~/app
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-app{{ checksum "package.json" }}
            - restore_cache:
                key: dependency-cache-npm{{ checksum "package.json" }}
            - restore_cache:
                key: dependency-cache-cache{{ checksum "package.json" }}
            - run:
                name: yarn setup
                command: yarn setup
            - run:
                name: yarn global add -g wait-on
                command: yarn global add -g wait-on            
            - save_cache:
                key: dependency-cache-app{{ checksum "package.json" }}
                paths:
                    - ~/app
            - save_cache:
                key: dependency-cache-npm{{ checksum "package.json" }}
                paths:
                    - ~/.npm
            - save_cache:
                key: dependency-cache-cache{{ checksum "package.json" }}
                paths:
                    - ~/.cache
            - persist_to_workspace:
                root: ~/
                paths:
                    - app
