# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1    

# end to end testing template
e2e_tests: &e2e_tests
    - run: npm run test:generate-app -- $DB_STRING
    - run: npm run test:start-app & wait-on http://localhost:1337
    - run: npm run test:e2e

# Define the jobs
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:11.14.0
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: run-setup-ci
                command: sudo npm run setup:ci
            - run:
                name: install-npm-wee
                command: sudo npm install -g wait-on
            - run:
                name: snyk
                command: sudo node ./node_modules/.bin/snyk auth ${SNYK_TOKEN} && sudo npm run test:snyk
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ~/app
    test:
        working_directory: ~/app
        docker:
            - image: circleci/node:11.14.0
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            # - run:
            #     name: test
            #     command: sudo node ./node_modules/.bin/snyk auth ${SNYK_TOKEN} && sudo npm run test:snyk
            - run:
                name: test-lint
                command: sudo npm run lint
            - run:
                name: test-unit
                command: sudo npm run test:unit
            - run:
                name: test-front
                command: sudo npm run test:front

    e2e_tests_postgres:
        docker:
            - image: circleci/node:11.14.0
            - image: circleci/postgres:9.6-alpine
        steps:            
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - <<: *e2e_tests
        

    # e2e_test_mysql:
    #     docker:
    #         - image: circleci/node:11.14.0
    #         - image: circleci/mysql

    # e2e_test_sqllite:
    #     docker:
    #         - image: circleci/node:11.14.0
    #         - image: circleci/postgres:9.6-alpine

    # e2e_test_mongo:
    #     docker:
    #         - image: circleci/node:11.14.0
    #         - image: circleci/postgres:mongo

workflows:
  version: 2
  build_and_test:
    jobs:   
        - build
        - test:
            requires:
                - build