name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - name: npm install, build, and test
      uses: docker://node:10
      run: |
        yarn setup
        yarn run -s lint
        yarn run -s test:unit
        yarn run -s test:front
